### ISSUE TITLE
已关闭

### ISSUE THREAD

**Issue by star7th** [giscafer/lodash.zh_CN.js#1]
https://github.com/star7th/showdoc github上编辑多目录api文档不方便，用这个会方便点

**Comment by giscafer** [comment]
@star7th 谢谢，写的不错，样式和布局可以再好好弄弄。lodash.js api文档很好，用的是jsdoc。
你可以参考这种 https://lodash.com/docs
另外建议，依赖环境不要太多，php不会玩；我用的话会选择nodejs环境支持的jsdoc或dox

**Comment by star7th** [comment]
好的，我参考下它的样式
